apiVersion: v1
kind: ReactionProvider
name: SyncVectorStore
spec:
  services:
    reaction:
      image: reaction-sync-vectorstore
      dapr:
        app-port: "80"
        app-protocol: "http"
  config_schema:
    type: object
    properties:
      vectorStoreType:
        type: string
        enum: ["Qdrant", "AzureAISearch", "InMemory"]
        default: "Qdrant"
      connectionString:
        type: string
        description: "Connection string for the vector store"
      embeddingServiceType:
        type: string
        enum: ["AzureOpenAI", "OpenAI"]
        default: "AzureOpenAI"
      embeddingEndpoint:
        type: string
        description: "Endpoint for the embedding service"
      embeddingApiKey:
        type: string
        description: "API key for the embedding service"
      embeddingModel:
        type: string
        default: "text-embedding-3-large"
      embeddingDimensions:
        type: integer
        default: 3072
      batchSize:
        type: integer
        default: 100
      maxRetries:
        type: integer
        default: 3
      retryDelayMs:
        type: integer
        default: 1000
    required:
      - vectorStoreType
      - connectionString
      - embeddingServiceType
      - embeddingApiKey