apiVersion: v1
kind: ReactionProvider
name: SyncDaprStateStore
spec:
  services:
    reaction:
      image: reaction-sync-dapr-statestore
---
apiVersion: v1
kind: ReactionProvider
name: PostDaprPubSub
spec:
  services:
    reaction:
      image: aman/reaction-post-dapr-pubsub:local-fix
      externalImage: true
