apiVersion: v1
kind: ContinuousQuery
name: orders-for-product
spec:
  mode: query
  sources:    
    subscriptions:
      - id: orders-source
        nodes:
          - sourceLabel: orders
        pipeline:
          - decode_value
          - parse_value
          - promote_order_details
          - extract_order_items
      - id: products-source
        nodes:
          - sourceLabel: products
        pipeline:
          - decode_value
          - parse_value
          - promote_product_details
      - id: reviews-source
        nodes:
          - sourceLabel: reviews
        pipeline:
          - decode_value
          - parse_value
          - promote_review_details
    middleware:
      - name: decode_value
        kind: decoder
        encoding_type: base64
        target_property: value
        strip_quotes: true
      - name: parse_value
        kind: parse_json
        target_property: value
        output_property: parsed_properties
      - name: promote_review_details
        kind: promote
        mappings:
          - path: "$.parsed_properties.review_id"
            target_name: "reviewId"
          - path: "$.parsed_properties.product_id"
            target_name: "productId"
          - path: "$.parsed_properties.rating"
            target_name: "rating"
      - name: promote_order_details
        kind: promote
        mappings:
          - path: "$.parsed_properties.order_id"
            target_name: "orderId"
          - path: "$.parsed_properties.items"
            target_name: "orderItems"
      - name: promote_product_details
        kind: promote
        mappings:
          - path: "$.parsed_properties.product_id"
            target_name: "productId"
          - path: "$.parsed_properties.product_name"
            target_name: "productName"
          - path: "$.parsed_properties.product_description"
            target_name: "productDescription"
      - name: extract_order_items
        kind: unwind
        orders:
          - selector: $.orderItems[*]
            label: orderItem
            key: $.product_id
            relation: ITEM_OF_ORDER
    joins:
      - id: REVIEW_TO_PRODUCT
        keys:
          - label: products
            property: productId
          - label: reviews
            property: productId
      - id: PRODUCT_TO_ORDER_ITEM
        keys:
          - label: products
            property: productId
          - label: orderItem
            property: product_id
  query: >
    MATCH
        (o:orders)-[:ITEM_OF_ORDER]->(oi:orderItem),
        (p:products)-[:PRODUCT_TO_ORDER_ITEM]->(oi)
    WHERE
        p.productId = 1010
    RETURN
        p.productId AS productId,
        o.orderId AS orderId,
        oi.quantity AS quantity