apiVersion: v1
kind: ContinuousQuery
name: customers-query
spec:
  mode: query
  sources:    
    subscriptions:
      - id: customers-source
        nodes:
          - sourceLabel: customers
        pipeline:
          - decode_value
          - parse_value
          - promote_customer_details
    middleware:
      - name: decode_value
        kind: decoder
        encoding_type: base64
        target_property: value
        strip_quotes: true
      - name: parse_value
        kind: parse_json
        target_property: value
      - name: promote_customer_details
        kind: promote
        mappings:
          - path: "$.value.customer_id"
            target_name: "customerId"
          - path: "$.value.customer_name"
            target_name: "customerName"
          - path: "$.value.loyalty_tier"
            target_name: "loyaltyTier"
          - path: "$.value.email"
            target_name: "email"
  query: >
    MATCH
        (c:customers)
    RETURN
        c.customerId AS customerId,
        c.customerName AS customerName,
        c.loyaltyTier AS loyaltyTier,
        c.email AS email