apiVersion: v1
kind: ContinuousQuery
name: orders-query
spec:
  mode: query
  sources:    
    subscriptions:
      - id: orders-source
        nodes:
          - sourceLabel: orders
        pipeline:
          - decode_value
          - parse_value
          - promote_order_details
          - extract_order_items
    middleware:
      - name: decode_value
        kind: decoder
        encoding_type: base64
        target_property: value
        strip_quotes: true
      - name: parse_value
        kind: parse_json
        target_property: value
        output_property: parsed_properties
      - name: promote_order_details
        kind: promote
        mappings:
          - path: "$.parsed_properties.order_id"
            target_name: "orderId"
          - path: "$.parsed_properties.customer_id"
            target_name: "customerId"
          - path: "$.parsed_properties.items"
            target_name: "orderItems"
          - path: "$.parsed_properties.status"
            target_name: "orderStatus"
      - name: extract_order_items
        kind: unwind
        orders:
          - selector: $.orderItems[*]
            label: orderItem
            key: $.product_id
            relation: ITEM_OF_ORDER
  query: >
    MATCH
        (o:orders)-[:ITEM_OF_ORDER]->(oi:orderItem)
    RETURN
        o.orderId AS orderId,
        o.customerId AS customerId,
        o.orderStatus AS orderStatus,
        oi.quantity AS quantity,
        oi.product_id AS productId
        