apiVersion: v1
kind: Pod
metadata:
  name: my-app-1
spec:
  containers:
    - name: app
      image: "ghcr.io/drasi-project/my-app:0.1"
---
apiVersion: v1
kind: Pod
metadata:
  name: my-app-2
spec:
  containers:
    - name: app
      image: "ghcr.io/drasi-project/my-app:0.2"
