name: Gemini Hello World

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Install and run Gemini CLI
        uses: google-gemini/gemini-cli-action@main
        with:
          prompt: 'Say "Hello world!"'
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
